import {Bittrex} from "../remote/bittrex";
import {CurrencyPair} from "../types/CurrencyPair";
import {CombinedOrderBook} from "./CombinedOrderBook";
import {Poloniex} from "../remote/poloniex";

export class OrderBookService {
  /**
   * handler is registered with bittrex and poloniex clients
   * triggered each time an update is pushed for an order book
   * propagates update to browserConectionManager
   * */
  onChange?: (pair: CurrencyPair) => void

  /**
   * Exchange clients
   * Each has its own copy of the order books for each of the currency pairs
   * */
  private poloniex: Poloniex
  private bittrex: Bittrex;

  /**
   * Combined order books for each currency pair
   * Generated by combining bittrex and poloniex data
   * */
  books: { [pair in CurrencyPair]: CombinedOrderBook }

  constructor(bittrex: Bittrex, poloniex: Poloniex) {
    this.bittrex = bittrex;
    this.bittrex.onChange = this.orderBookUpdateHandler;
    this.poloniex = poloniex;
    this.poloniex.onChange = this.orderBookUpdateHandler;
    this.books = {
      [CurrencyPair.BTC_ETH]: new CombinedOrderBook(this.bittrex.BTC_ETH, this.poloniex.BTC_ETH),
      [CurrencyPair.BTC_DOGE]: new CombinedOrderBook(this.bittrex.BTC_DOGE, this.poloniex.BTC_DOGE)
    };
  }

  orderBookUpdateHandler = (pair: CurrencyPair) => {
    this.onChange?.(pair);
  }
}